# Generated by Django 5.1.2 on 2025-03-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreatApp', '0003_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
