# Generated by Django 5.1.2 on 2025-03-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreatApp', '0004_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_amh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_amh',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
